/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import Cliente.Cliente;
import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author joaop
 */
public class ClienteGUI extends javax.swing.JFrame {
    private final Cliente cliente  = new Cliente();
    /**
     * Creates new form ClienteInter
     */
    public ClienteGUI() {
        initComponents();
        jpFilme.setVisible(false);
        jpNota.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpNome = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jpNota = new javax.swing.JPanel();
        lbNota = new javax.swing.JLabel();
        cmbNota = new javax.swing.JComboBox<>();
        jpFilme = new javax.swing.JPanel();
        lbFilme = new javax.swing.JLabel();
        cmbFilme = new javax.swing.JComboBox<>();
        jpRequisicao = new javax.swing.JPanel();
        lbRequsicao = new javax.swing.JLabel();
        cmbRequisicao = new javax.swing.JComboBox<>();
        btEnviarRequisicao = new javax.swing.JButton();
        jpPainelServidor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResposta = new javax.swing.JTextArea();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente-Servidor");

        jPanel2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Dados Cliente");

        jpNome.setLayout(new java.awt.GridLayout(1, 2, -92, 15));

        lbNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbNome.setText("Nome");
        jpNome.add(lbNome);
        jpNome.add(txtNome);

        jpNota.setLayout(new java.awt.GridLayout(1, 2, -92, 15));

        lbNota.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbNota.setText("Nota");
        jpNota.add(lbNota);

        cmbNota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Ruim", "2 - Bom", "3 - Ótimo" }));
        cmbNota.setSelectedIndex(-1);
        jpNota.add(cmbNota);

        jpFilme.setLayout(new java.awt.GridLayout(1, 2, -92, 15));

        lbFilme.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbFilme.setText("Filme");
        jpFilme.add(lbFilme);

        cmbFilme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Origem", "Interestelar", "Gravidade", "O Poderoso Chefão", "Pulp Fiction", "Clube da Luta", "Forrest Gump", "Cidade de Deus", "Vingadores: Ultimato", "O Senhor dos Anéis", "Coringa", "O Iluminado", "Cisne Negro", "Titanic", "O Rei Leão", "Harry Potter", "O Labirinto do Fauno", "Gladiador", "O Quinto Elemento", "E.T. - O Extraterrestre" }));
        cmbFilme.setSelectedIndex(-1);
        jpFilme.add(cmbFilme);

        jpRequisicao.setLayout(new java.awt.GridLayout(1, 2, -90, 15));

        lbRequsicao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbRequsicao.setText("Requisitar:");
        jpRequisicao.add(lbRequsicao);

        cmbRequisicao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbRequisicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filmes não avaliados", "Avaliar filme", "Solicitar recomendação", "Avaliações efetuadas" }));
        cmbRequisicao.setSelectedIndex(-1);
        cmbRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRequisicaoActionPerformed(evt);
            }
        });
        jpRequisicao.add(cmbRequisicao);

        btEnviarRequisicao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btEnviarRequisicao.setText("Enviar");
        btEnviarRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarRequisicaoActionPerformed(evt);
            }
        });

        jpPainelServidor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpPainelServidor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Resposta do Servidor");
        jpPainelServidor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        txtResposta.setEditable(false);
        txtResposta.setColumns(20);
        txtResposta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtResposta.setRows(5);
        jScrollPane2.setViewportView(txtResposta);

        jpPainelServidor.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 300, 370));

        btCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btEnviarRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpRequisicao, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(jpFilme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpNota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)))
                .addComponent(jpPainelServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jpPainelServidor, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jpRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jpFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jpNota, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEnviarRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRequisicaoActionPerformed
        String selectedOption = (String) cmbRequisicao.getSelectedItem();
         Object[] objetos;
        if (cmbRequisicao.getSelectedItem() != null && selectedOption.equals("Avaliar filme")) {
            jpFilme.setVisible(true);
            jpNota.setVisible(true);
        }else{
            jpFilme.setVisible(false);
            jpNota.setVisible(false);
        }
    }//GEN-LAST:event_cmbRequisicaoActionPerformed

    
    
    private boolean validarCampos( String selectedOption){
        String msgErro = "";

        if(selectedOption == null || selectedOption.isEmpty()){
            msgErro += "Insira uma opção de requisição!\n";
        }else if (selectedOption.equals("Avaliar filme")) {
            if(cmbNota.getSelectedItem() == null || cmbFilme.getSelectedItem() == null || txtNome.getText().isEmpty()){
                msgErro += "Preencha todos os campos!\n";
            }
        }

        
        
        if(msgErro.isEmpty()){
            return true;
        }else{
            JOptionPane.showMessageDialog(this, msgErro, "Verifique os campos e tente novamente", JOptionPane.ERROR_MESSAGE);
            return false; 
        }
    }
    
    
    private void btEnviarRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarRequisicaoActionPerformed
         String selectedOption = (String) cmbRequisicao.getSelectedItem();
         Object[] objetos;
        if (validarCampos(selectedOption)) {
            switch (selectedOption) {
                case "Filmes não avaliados":
                    objetos = new Object[] {1, txtNome.getText()};
                    enviarRequisicao(objetos);
                    break;
                case "Avaliar filme":
                    jpFilme.setVisible(true);
                    jpNota.setVisible(true);
                    String nota = cmbNota.getSelectedItem().toString();
                    objetos = new Object[] {2, txtNome.getText(), cmbFilme.getSelectedItem().toString(), nota.charAt(0)};
                    enviarRequisicao(objetos);
                    break;
                case "Solicitar recomendação":
                    objetos = new Object[] {3, txtNome.getText()};
                    enviarRequisicao(objetos);
                    break;
                case "Avaliações efetuadas":
                    objetos = new Object[] {4, txtNome.getText()};
                    enviarRequisicao(objetos);
                    break;
            }
        }
    }//GEN-LAST:event_btEnviarRequisicaoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        txtNome.setText("");
        cmbFilme.setSelectedIndex(-1);
        cmbNota.setSelectedIndex(-1);
        cmbRequisicao.setSelectedIndex(-1);
        
    }//GEN-LAST:event_btCancelarActionPerformed

    private <T> String concatenarArray(T[] array) {
        StringBuilder result = new StringBuilder();

        for (int i = 0; i < array.length; i++) {
            result.append(array[i]);

            if (i < array.length - 1) {
                result.append(";"); // Adiciona ponto e vírgula entre os valores
            }
        }

        return result.toString();
    }



    private void enviarRequisicao(Object[] array) {
        String mensagem = concatenarArray(array);
        String resposta = cliente.enviaMensagem(mensagem);
        txtResposta.setText(resposta);
    }
    

    
                
                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLighLaf and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        //Setando um tema de um repositório externo
        try {
            UIManager.setLookAndFeel( new FlatDarkLaf() );
        } catch( UnsupportedLookAndFeelException ex ) {
            System.err.println( "Falha ao iniciar tema FlatLightLaf" );
        }catch (Exception ex) {
            System.err.println( "Falha ao definir tema" );
        } 
        //</editor-fold>
        
        // TRADUÇÃO
        javax.swing.UIManager.put("OptionPane.yesButtonText", "Sim"); 
        javax.swing.UIManager.put("OptionPane.noButtonText", "Não");
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ClienteGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEnviarRequisicao;
    private javax.swing.JComboBox<String> cmbFilme;
    private javax.swing.JComboBox<String> cmbNota;
    private javax.swing.JComboBox<String> cmbRequisicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpFilme;
    private javax.swing.JPanel jpNome;
    private javax.swing.JPanel jpNota;
    private javax.swing.JPanel jpPainelServidor;
    private javax.swing.JPanel jpRequisicao;
    private javax.swing.JLabel lbFilme;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNota;
    private javax.swing.JLabel lbRequsicao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtResposta;
    // End of variables declaration//GEN-END:variables

    
    
}
