/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import Cliente.Cliente;

/**
 *
 * @author joaop
 */
public class ClienteGUI extends javax.swing.JFrame {
    private final Cliente cliente = new Cliente();
    /**
     * Creates new form ClienteInter
     */
    public ClienteGUI() {
        initComponents();
        jpFilme.setVisible(false);
        jpNota.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpNome = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jpNota = new javax.swing.JPanel();
        lbNota = new javax.swing.JLabel();
        cmbNota = new javax.swing.JComboBox<>();
        jpFilme = new javax.swing.JPanel();
        lbFilme = new javax.swing.JLabel();
        txtFilme = new javax.swing.JTextField();
        jpRequisicao = new javax.swing.JPanel();
        lbRequsicao = new javax.swing.JLabel();
        cmbRequisicao = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResposta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Dados Cliente");

        jpNome.setLayout(new java.awt.GridLayout(1, 2, -92, 15));

        lbNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbNome.setText("Nome");
        jpNome.add(lbNome);
        jpNome.add(txtNome);

        jpNota.setLayout(new java.awt.GridLayout(1, 2, -92, 15));

        lbNota.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbNota.setText("Nota");
        jpNota.add(lbNota);

        cmbNota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Ruim", "2 - Bom", "3 - Ótimo" }));
        cmbNota.setSelectedIndex(-1);
        jpNota.add(cmbNota);

        jpFilme.setLayout(new java.awt.GridLayout(1, 2, -92, 15));

        lbFilme.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbFilme.setText("Filme");
        jpFilme.add(lbFilme);
        jpFilme.add(txtFilme);

        jpRequisicao.setLayout(new java.awt.GridLayout(1, 2, -90, 15));

        lbRequsicao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbRequsicao.setText("Requisitar:");
        jpRequisicao.add(lbRequsicao);

        cmbRequisicao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbRequisicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filmes não avaliados", "Avaliar filme", "Solicitar recomendação", "Avaliações efetuadas" }));
        cmbRequisicao.setSelectedIndex(-1);
        cmbRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRequisicaoActionPerformed(evt);
            }
        });
        jpRequisicao.add(cmbRequisicao);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpRequisicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(jpFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpNota, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 360, 370));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Resposta do Servidor");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        txtResposta.setColumns(20);
        txtResposta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtResposta.setRows(5);
        jScrollPane2.setViewportView(txtResposta);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 340, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 360, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRequisicaoActionPerformed
        String selectedOption = (String) cmbRequisicao.getSelectedItem();
         Object[] objetos;
        if (selectedOption.equals("Avaliar filme")) {
            jpFilme.setVisible(true);
            jpNota.setVisible(true);
        }else{
            jpFilme.setVisible(false);
            jpNota.setVisible(false);
        }
    }//GEN-LAST:event_cmbRequisicaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String selectedOption = (String) cmbRequisicao.getSelectedItem();
         Object[] objetos;
        if (selectedOption != null) {
            switch (selectedOption) {
                case "Filmes não avaliados":
                    objetos = new Object[] {1, txtNome.getText()};
                    enviarRequisicao(objetos);
                    break;
                case "Avaliar filme":
                    jpFilme.setVisible(true);
                    jpNota.setVisible(true);
                    String nota = cmbNota.getSelectedItem().toString();
                    objetos = new Object[] {2, txtNome.getText(), txtFilme.getText(), nota.charAt(0)};
                    enviarRequisicao(objetos);
                    break;
                case "Solicitar recomendação":
                    objetos = new Object[] {3, txtNome.getText()};
                    enviarRequisicao(objetos);
                    break;
                case "Avaliações efetuadas":
                    objetos = new Object[] {4, txtNome.getText()};
                    enviarRequisicao(objetos);
                    break;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private <T> String concatenarArray(T[] array) {
        StringBuilder result = new StringBuilder();

        for (int i = 0; i < array.length; i++) {
            result.append(array[i]);

            if (i < array.length - 1) {
                result.append(";"); // Adiciona ponto e vírgula entre os valores
            }
        }

        return result.toString();
    }



    private void enviarRequisicao(Object[] array) {
        String mensagem = concatenarArray(array);
        String resposta = cliente.enviaMensagem(mensagem);
        txtResposta.setText(resposta);
    }
    

    
                
                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ClienteGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbNota;
    private javax.swing.JComboBox<String> cmbRequisicao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpFilme;
    private javax.swing.JPanel jpNome;
    private javax.swing.JPanel jpNota;
    private javax.swing.JPanel jpRequisicao;
    private javax.swing.JLabel lbFilme;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNota;
    private javax.swing.JLabel lbRequsicao;
    private javax.swing.JTextField txtFilme;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtResposta;
    // End of variables declaration//GEN-END:variables

    
    
}
